[package]
name = "cloudflare"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
hyper = { version = "0.14", default-features = false }
# Specify updated version directly from the repository since it has
# strict version of `wasm-bindgen` that are conficting with opentelemetry-tracing
# crate from root. Git version has a higher version that removes the conflict
worker = { git = "https://github.com/cloudflare/workers-rs", rev = "c57f7a6d31da601397e46daec5a9448d6efbe1cc" } # version = "0.18"
tailcall = {path = "..", default-features = false}
lazy_static = { version = "1.4.0", features = [] }

[profile.release]
lto = true
strip = true
codegen-units = 1
opt-level = 'z'